//
//  MenuBarBatteryGlyph.swift
//
//  The controller's charge in the menu bar, as a battery rather than a number.
//  This file only picks a NAME; the art is generated by
//  scripts/generate-controller-battery.swift, which carries the drawing and the
//  geometry it was matched to.
//
//  WHY THE PAD AND THE BATTERY ARE ONE IMAGE. `MenuBarExtra(.menu)` renders its
//  label into an NSStatusItem button, and that button has exactly one image and
//  one title. Probed in the real menu bar (2026-09-11), which is the only place
//  this is observable - nothing errors, things just silently don't draw:
//
//    * an HStack of two bare `Image(systemName:)`s renders only the FIRST
//    * `Image(nsImage:)` renders nothing at all, with or without
//      `.renderingMode(.template)` or `.resizable().frame()`
//    * attaching an `.overlay { }` to an `Image(systemName:)` makes the Image
//      itself disappear too
//    * `Label("75%", systemImage:)` drops the title; `HStack { Image; Text }`
//      keeps both, because those are the button's two slots
//
//  So a battery beside the pad cannot be composed at runtime, and a battery
//  drawn at runtime cannot be handed over either. One baked image per level is
//  the only shape that works - which is fine, because it also means the fill can
//  be continuous instead of quantised to the five levels SF Symbols ships.
//

import Foundation

enum MenuBarBatteryGlyph {

    /// The levels there is art for - the eleven a DualSense actually reports
    /// (its HID status byte carries a 0...10 level), so this neither invents
    /// precision nor throws any away.
    static let step = 10

    /// Asset naming the pad-and-battery mark for a reading. Out-of-range input
    /// is clamped rather than trusted: the level arrives from a raw HID decode
    /// or from GameController, which disagree at the edges, and a name with no
    /// asset behind it draws NOTHING in the menu bar - silently, which is the
    /// worst way for this to fail.
    static func assetName(forPercent percent: Int, charging: Bool) -> String {
        let clamped = min(max(percent, 0), 100)
        let level = Int((Double(clamped) / Double(step)).rounded()) * step
        return "ControllerBattery\(level)\(charging ? "Charging" : "")"
    }
}
